### ISSUE TITLE
RFE: Support holding packages by name only

### ISSUE THREAD

**Issue by noelmcloughlin** [saltstack-formulas/packages-formula#11]
The formula currently supports holding **packages by name: version** .

We should also support **packages by name only**, the following pillar data for example. 

```
    held:
      - xserver-xorg
      - xserver-xorg-core
      - kernel-4.13.0-36-generic

[CRITICAL]  Rendering SLS 'base:packages.pkgs' failed: Jinja variable 'list object' has no attribute 'items'.
```

**Comment by noelmcloughlin** [comment]
@javierbertoli  Just to confirm this works on Ubuntu. I'm happy. Thanks.

If same package appears in `held` and `wanted` lists, there is some noise.  I resolved this by removing from `wanted` list.
```

          ID: held_pkgs
    Function: pkg.installed
      Result: True
     Comment: All specified packages are already installed.
              Package xserver-xorg-core is now being held..
              Package xserver-xorg-hwe-16.04 is now being held..
              Package linux-image-4.13.0-36-generic is already set to be held.
     Started: 15:43:58.351919
    Duration: 1804.485 ms
     Changes:   
              ----------
              xserver-xorg-core:
                  ----------
                  new:
                      hold
                  old:
                      None
              xserver-xorg-hwe-16.04:
                  ----------
                  new:
                      hold
                  old:
                      install
----------
          ID: wanted_pkgs
    Function: pkg.installed
      Result: True
     Comment: All specified packages are already installed.
              Package iptables is already set not to be held..
              Package lsb-core is already set not to be held..
              Package apt-transport-https is already set not to be held..
              Package ca-certificates is already set not to be held..
              Package ssh is already set not to be held.
     Started: 15:44:00.170688
    Duration: 1676.208 ms
     Changes: 
```

**Negative testing.**
          ID: wanted_pkgs
    Function: pkg.installed
      Result: False
     Comment: Problem encountered installing package(s). Additional info follows:
              
              errors:
                  - Running scope as unit run-rab423f44f41349b08f95d29ddf3cf596.scope.
                    E: Unable to correct problems, you have held broken packages.
     Started: 15:33:39.619390
    Duration: 9251.92 ms
     Changes:

**Comment by javierbertoli** [comment]
> If same package appears in held and wanted lists, there is some noise. I resolved this by removing from wanted list.

@noelmcloughlin, I mentioned this situation in the README:

> * ``wanted``: a list of packages which will be installed. Packages in this
  list will be automatically unheld so, if you want to permanently unheld a
  package you were previously helding to a version, just move it from the
  ``held`` dict to this list.

Maybe we need to rephrase that or explain it better?

**Comment by noelmcloughlin** [comment]
@javierbertoli Sure, rephrasing is always worth considering if you like, but readme is understandable.

Currently I'm troubleshooting another apt issue - likely an OS baseline or pillar are wrong. 
 I'll raise an issue if I find any useful learnings to be shared in README.
```
[ERROR   ] stderr: Running scope as unit run-rdf4057fe21614b41a0753a6bcce057e5.scope.
E: Unable to correct problems, you have held broken packages.
[ERROR   ] retcode: 100
[ERROR   ] Problem encountered installing package(s). Additional info follows:
```

**Comment by noelmcloughlin** [comment]
Okay, that error happens on formula reruns. So if package:version is **already held** and current run has same pillars, then apt throws that ERROR back to salt.

**Comment by javierbertoli** [comment]
@noelmcloughlin Sorry, missed this comments. I can't reproduce your error. 

* On the kitchen-tests I keep the instance up with `kitchen test --destroy=never deb-debian-9` and then, on re-runs (`kitchen converge deb-debian-9`) I just get

```
[INFO    ] All specified packages are already installed and are at the desired 
Package alien is already set to be held.
Package iotop is already set to be held.
```

* And on my hosts, holding a package

```
----------
          ID: held_pkgs
    Function: pkg.installed
      Result: True
     Comment: All specified packages are already installed.
              Package docker-engine is now being held.
     Started: 16:31:56.523659
    Duration: 204.036 ms
     Changes:   
              ----------
              docker-engine:
                  ----------
                  new:
                      hold
                  old:
                      install
...
...
Succeeded: 150 (changed=1)
Failed:      0
```
and on re-reruns
```
----------
          ID: held_pkgs
    Function: pkg.installed
      Result: True
     Comment: All specified packages are already installed.
              Package docker-engine is already set to be held.
     Started: 16:38:43.488878
    Duration: 46.388 ms
     Changes:   
```

As [your previous comment](https://github.com/saltstack-formulas/packages-formula/issues/11#issuecomment-371122280) seems to show an versions inconsistency issue (holding packages that do not exist anymore, perhaps?), might that be related? Or else, an issue on the salt-minion version? (I'm using 2017.7.4+ds-1)

Anything else I can do to help you debug this issue?

**Comment by noelmcloughlin** [comment]
Hey @javierbertoli 
I tried and failed to reproduce this during the week so we can assume it was the pillar data at the time was to blame. I've being adjusting my pillars since then.  The held feature works on first and reruns.  

Thanks for Looking

**Comment by javierbertoli** [comment]
You're welcome! :smile:
