### ISSUE TITLE
Bug with snap.sls breaks pkgs.purged

### ISSUE THREAD

**Issue by noelmcloughlin** [saltstack-formulas/packages-formula#17]
PR #13 introduced a bug. The bug is related to #15 (how best to use extends). 

Basically`**unwanted packages** ` are not removed for some reason. 
My workaround was to remove `extend.unwanted_pkgs` stanza from snaps.sls
```
extend:
  unwanted_pkgs:
    pkg.removed:
      - pkgs: {{ packages.snaps.collides }}
    {% if req_states %}
      - require:
      {% for dep in req_states %}
        - sls: {{ dep }}
      {% endfor %}
    {% endif %}

```
**Pillars tested**  
```
packages:
  pips:
    wanted:
      - docker
    unwanted:
       - docker-py
  pkgs:
    unwanted:
      - unattended-upgrades
      - avahi-daemon
      - lxc-docker*
      - docker.io*
      - unattended-upgrades
    held:
      - xserver-xorg-core: '2:1.18*'
    wanted:
      - iptables
      - ca-certificates
      - apt-transport-https
      - python-apt
  snaps:
    wanted:
      - hello-world
    unwanted:
      - goodbye-world
```

Once the `snaps.extends.unwanted_pkgs` is removed formula works.
```
[INFO    ] Executing state pkg.purged for [unwanted_pkgs]
...
[INFO    ] Executing command ['systemd-run', '--scope', 'apt-get', '-q', '-y', 'purge', 'unattended-upgrades'] in directory '/home/messi'
[TRACE   ] stdout: Reading package lists...
Building dependency tree...
Reading state information...
The following packages will be REMOVED:
  unattended-upgrades*

**Comment by noelmcloughlin** [comment]
@javierbertoli @vunty @aboe76  Does anyone have experience with using `extends` properly?

**Comment by javierbertoli** [comment]
@noelmcloughlin, I see no snapd packages in that pillar. Is that the whole pillar,  something is missing there or you mean that, with *that* pillar, `snaps.sls fails`? 

Asking so I can try to reproduce the error (which, if you can paste it too, it'd be great :smile:).

**Comment by noelmcloughlin** [comment]
Hi @javierbertoli I updated the problem description. There is no error just does not work.
I think `snaps.extends.unwanted_pkgs.pkgs` is overwriting `pkgs.unwanted_pkgs.pkgs` instead of extending the list.  So `wanted_pkgs` is probably not working also.

**Comment by javierbertoli** [comment]
He... we should probably add some tests and see they pass. I'll see if I can check on that tomorrow

**Comment by javierbertoli** [comment]
@noelmcloughlin checking this, it seems the issue is not related to the state or extent, but to the testing platform: apparently, snaps can't be run that 'easily' in docker containers.

When testing our setup, I get this error in the vm:

```
-- Unit snap-core-4206.mount has begun starting up.
Mar 22 13:21:47 d293a697e453 kernel: loop: module loaded
Mar 22 13:21:48 d293a697e453 systemd[1]: snap-core-4206.mount: Mount process exited, code=exited status=32
Mar 22 13:21:48 d293a697e453 systemd[1]: Failed to mount Mount unit for core.
-- Subject: Unit snap-core-4206.mount has failed
```
Reading around, I got to [this link](https://github.com/nextcloud/nextcloud-snap/issues/212) and googling, to [this](https://forum.snapcraft.io/t/running-snaps-inside-docker-containers/869)

As I mentioned previouly (at least, I think I did), I don't use snaps, so I'm learning on the go, and probably not the one to say what can or can't be done with snaps :smile:, so I'll leave these links so you can consider them. 

Am I understanding those links correctly? Are you trying to run snaps in docker? If so, perhaps we can switch the testing environment to vagrant (at least, to get this running?

**Comment by noelmcloughlin** [comment]
Hi @javierbertoli No, I'm not using docker for the UC.  BTW, the bug affects unwanted RPM/DEB packages, not snaps/pips/gems pillars.

To replicated.
Add few unwanted packages to your `packages.pkgs.unwanted` pillar.
Ensure your highstate includes `packages.pkg` and `packages.snaps`
Run the highstate

Bug
Unwanted DEB/RPM/ETC packages are not removed.

Workaround:
remove the `snaps.extend.unwanted_pkgs` stanza from snaps.sls

**Comment by noelmcloughlin** [comment]
The snaps problem in docker needs separate issue raised.

**Comment by javierbertoli** [comment]
> The snaps problem in docker needs separate issue raised.

Gotcha. 

> the bug affects unwanted RPM/DEB packages, not snaps/pips/gems pillars.

Probably this [extend of the `unwanted_pkgs`](https://github.com/saltstack-formulas/packages-formula/blob/master/packages/snaps.sls#L19) is the one overriding the list of unwanted pkgs?

**Comment by noelmcloughlin** [comment]
Yes, I think that extend is overriding `unwanted_pkgs` and probably `pkg_req_pkgs` too.  

Do you know the correct syntax needed for extending a list?

**Comment by javierbertoli** [comment]
According to [the documentation](https://docs.saltstack.com/en/latest/ref/states/extend.html) extend *overrides* resources attributes and *does not* "append* to them. Ie,

```yaml

resource:
  attribute_1: A
  ...

extend:
  resource:
    attribute_1: B
```
will  **NOT** end up producing `attribute_1: [A, B]`, but just `attribute_1: B`

This is the case with [this line in `snaps.sls`](https://github.com/saltstack-formulas/packages-formula/blob/master/packages/snaps.sls#L19) overriding [this one in `pkgs.sls`](https://github.com/saltstack-formulas/packages-formula/blob/master/packages/pkgs.sls#L57).

Pushed #18 to address this issue.
