### ISSUE TITLE
pip.installed reload_modules true

### ISSUE THREAD

**Issue by noelmcloughlin** [saltstack-formulas/packages-formula#3]
Might be useful to include `reload_modules: True` in pip.installed function so modules get refreshed.

**Comment by noelmcloughlin** [comment]
Thanks. I  wonder if its needed (supported) by pip.remove too?

**Comment by javierbertoli** [comment]
I didn't see that option in [pip.removed](https://docs.saltstack.com/en/latest/ref/states/all/salt.states.pip_state.html#salt.states.pip_state.removed) documentation. Am I right?

**Comment by noelmcloughlin** [comment]
Sometimes docs are missing parameters.  But issue is fixed anyway. Thx.
