### ISSUE TITLE
problem with UTF?

### ISSUE THREAD

**Issue by mvivaldi** [saltstack-formulas/packages-formula#48]
I'm using this formula and since I installed salt 2019.2.0 I have this problem (tested in ubuntu 16.04 and redhat 6):
```
# salt-call state.apply packages 
[INFO    ] Loading fresh modules for state activity
[INFO    ] Running state [pkg_req_pkgs] at time 15:29:33.789483
[INFO    ] Executing state pkg.installed for [pkg_req_pkgs]
[INFO    ] Executing command [u'dpkg-query', u'--showformat', u'${Status} ${Package} ${Version} ${Architecture}', u'-W'] in directory '/root'
[INFO    ] Executing command [u'apt-cache', u'-q', u'policy', u"u'curl'"] in directory '/root'
[INFO    ] Executing command [u'apt-cache', u'-q', u'policy', u"u'gzip'"] in directory '/root'
[INFO    ] Executing command [u'apt-cache', u'-q', u'policy', u"u'bzip2'"] in directory '/root'
[INFO    ] Executing command [u'apt-get', u'-q', u'update'] in directory '/root'
[INFO    ] Executing command [u'dpkg', u'--get-selections', u'*'] in directory '/root'
[INFO    ] Executing command [u'systemd-run', u'--scope', u'apt-get', u'-q', u'-y', u'-o', u'DPkg::Options::=--force-confold', u'-o', u'DPkg::Options::=--force-confdef', u'install', u"u'curl'", u"u'gzip'", u"u'bzip2'"] in directory '/root'
[ERROR   ] Command '[u'systemd-run', u'--scope', u'apt-get', u'-q', u'-y', u'-o', u'DPkg::Options::=--force-confold', u'-o', u'DPkg::Options::=--force-confdef', u'install', u"u'curl'", u"u'gzip'", u"u'bzip2'"]' failed with return code: 100
[ERROR   ] stdout: Reading package lists...
Building dependency tree...
Reading state information...
[ERROR   ] stderr: Running scope as unit run-r08177169660649899531c302403fa65e.scope.
E: Unable to locate package u'curl'
E: Unable to locate package u'gzip'
E: Unable to locate package u'bzip2'
[ERROR   ] retcode: 100
[INFO    ] Executing command [u'dpkg-query', u'--showformat', u'${Status} ${Package} ${Version} ${Architecture}', u'-W'] in directory '/root'
[ERROR   ] Problem encountered installing package(s). Additional info follows:

errors:
    - Running scope as unit run-r08177169660649899531c302403fa65e.scope.
      E: Unable to locate package u'curl'
      E: Unable to locate package u'gzip'
      E: Unable to locate package u'bzip2'
```

I think there is a problem with UTF and python because the formula try to install the package  u'curl' instead of curl.

Thank you

EDIT: same problem with ubuntu 18.04 with salt python2, but there is no problem with ubuntu 18.04 and salt with python3

**Comment by javierbertoli** [comment]
As I understand you, the issue happens with salt 2019.2.x in  ubuntu 16.04, redhat 6 (both of which use python2) and ubuntu 18.04 also with python2, right?

IIRC I run against something like this in other formulas and [this change](https://docs.saltstack.com/en/latest/topics/releases/2018.3.0.html) is probably the cause of the issue. I think we'll need to fix it the way suggested there.

@mvivaldi can you provide an example of the pillar you're using, as to test it?

**Comment by mvivaldi** [comment]
yes, all the pc with python2 have the problem, no problem with python3

my pillar (super simple):

```
packages:
  pkgs:
    wanted:
      - mc
      - vim-nox
```

the state fail when it try to install the required pkgs, so before installing the packges in the pillar

**Comment by myii** [comment]
With `2019.2`, there are important [non-backwards compatible changes to the YAML renderer](https://docs.saltstack.com/en/develop/topics/releases/2019.2.0.html#non-backward-compatible-change-to-yaml-renderer).  The solution is to use the `|tojson` filter.  I haven't had any chance to look into it here but it would be worth checking with that filter set, particularly where [`.items`](https://github.com/saltstack-formulas/packages-formula/search?q=items&unscoped_q=items) is being used.
