### ISSUE TITLE
Update the formula to follow template-formula guidelines

### ISSUE THREAD

**Issue by javierbertoli** [saltstack-formulas/packages-formula#53]
Update the formula to follow the guidelines of [template-formula](https://github.com/saltstack-formulas/template-formula/) as much as possible.

**Comment by daks** [comment]
I'm working on implementing semantic-release and updating tests (which is a lot of work). I hope to have a PR soon.

**Comment by myii** [comment]
@daks A lot of the work has been done in #54.  It would be great if you can help to finialse it.

**Comment by myii** [comment]
Fixed by #61.
