### ISSUE TITLE
RFE: Generic Upgrade OS support wanted

### ISSUE THREAD

**Issue by noelmcloughlin** [saltstack-formulas/packages-formula#9]
This formula could include '`upgrade_os: True/False`' support.  This and #8 would be useful features.

**Comment by javierbertoli** [comment]
`upgrade_os`? can you provide a use case for this, or a description of what would this option do?

I'm trying to guess what you expect to do with this parameter, but if you mean 'manage a full os/system upgrade', then I think other formulas already provide better support for that? Ie, [the upgrade/dist_upgrade/unattended states in the apt formula](https://github.com/saltstack-formulas/apt-formula/tree/master/apt)

**Comment by noelmcloughlin** [comment]
This formula abstracts three use cases implemented by **generic package managers** (listed).  This formula also updates package database same as a generic package manager.

1. - install package(s)
2. - remove package(s)
3. - upgrade packages(s)

OS upgrade is UC3.  The formula only supports UC3 where target unit is package.  I would love the formula to support UC3 where target unit is OS.  Today I was updating a README with manual OS upgrade command before realizing salt formulas can and shoul do this.  I checked other formula, but **the feature belongs here** (imho, despite the bold emphasis ;-)  for better UC3 support.

**Comment by noelmcloughlin** [comment]
Closing until a firm use case presents.
